name: Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x', '18.x', '22.x']

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
